### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by t-muser**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by t-muser** [comment]
@conda-forge-admin, please rerender

**Comment by t-muser** [comment]
@conda-forge/core I'm at a loss at what is the best way to handle this. This package is purely python code (so `noarch: python` is appropriate), but when installing under python 3.13 with most package managers, I needed to explicitly specify the scipy version otherwise the install fails (see. bayesian-optimization/BayesianOptimization#534). Functionality-wise, any version of scipy should work, so specifying the version is purely to make the install possible.

**Comment by h-vetinari** [comment]
This shouldn't be necessary in conda-forge. We have no 3.13 builds for anything before scipy 1.14, so the solver has no other option than to take 1.14

**Comment by t-muser** [comment]
perfect, thanks!

**Pull request closed without merging**
